BEGIN;

ALTER TABLE IF EXISTS todos
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP WITH TIME ZONE;


ALTER TABLE IF EXISTS users
    ADD COLUMN password TEXT DEFAULT 'default123' NOT NULL;


CREATE TABLE IF NOT EXISTS user_session(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
user_id UUID NOT NULL REFERENCES users(id),
archived_at TIMESTAMP WITH TIME ZONE,
created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

COMMIT;